import './globals.css';
import Navbar from './components/Navbar/index';

export const metadata = {
  title: 'Geoapp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
